[project]
name = 'Decentralized-Healthcare-Telemedicine-Coordination'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.provider-verification]
path = 'contracts/provider-verification.clar'
clarity_version = 2
epoch = 2.5

[contracts.quality-assurance]
path = 'contracts/quality-assurance.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
